name: finance_app_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  blobs: ^2.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/profile_1.jpeg
    - assets/profile_2.jpeg
    - assets/profile_3.jpeg
    - assets/profile_4.jpeg
    - assets/profile_5.jpeg
    - assets/profile_6.jpeg
